language: python
python:
  - 2.7
before_install:
  - pip install coveralls
install:
  - pip install -r requirements.txt
script:
  - cd bertrade_api
  - coverage run -m unittest discover
  - coverage report --rcfile=../.coveragerc
after_success:
  - coveralls
